# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean <- function(x) {
    .Call(`_libaffyperftest_mean`, x)
}

col_means <- function(x) {
    .Call(`_libaffyperftest_col_means`, x)
}

naive_median1 <- function(x, na_rm = FALSE) {
    .Call(`_libaffyperftest_naive_median1`, x, na_rm)
}

naive_median2 <- function(x, na_rm = FALSE) {
    .Call(`_libaffyperftest_naive_median2`, x, na_rm)
}

naive_median3 <- function(x, na_rm = FALSE) {
    .Call(`_libaffyperftest_naive_median3`, x, na_rm)
}

median <- function(x) {
    .Call(`_libaffyperftest_median`, x)
}

col_medians <- function(x) {
    .Call(`_libaffyperftest_col_medians`, x)
}

rcpp_hello_world <- function() {
    .Call(`_libaffyperftest_rcpp_hello_world`)
}

tukey_biweight <- function(x, c = 5L, epsilon = 1e-04) {
    .Call(`_libaffyperftest_tukey_biweight`, x, c, epsilon)
}

col_tukey_biweights <- function(x, c = 5L, epsilon = 1e-04) {
    .Call(`_libaffyperftest_col_tukey_biweights`, x, c, epsilon)
}

